spring:
  config:
    import: "application-secret.yml"

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

  application:
    name: standard-service
  datasource:
    url: jdbc:sqlserver://${secret.mssql.endpoint};databaseName=${secret.mssql.db};encrypt=false;trustServerCertificate=true
    username: ${secret.mssql.username}
    password: ${secret.mssql.password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10       # 동시에 처리할 수 있는 최대 커넥션 수
      minimum-idle: 2            # 항상 유지할 유휴 커넥션 수
      idle-timeout: 300000  # 커넥션 유휴 시간 (밀리초)
      max-lifetime: 600000  # 커넥션 풀 커넥션 최대 수명

  jpa:
    hibernate:
      ddl-auto: none
#      show-sql: true
#      properties:
#        hibernate:
#          format_sql: true  # SQL 예쁘게 출력
    open-in-view: false  # JPA 세션 오픈 범위 제한 (N+1 찾을 때 이게 도움이 될 수 있음)

  jackson:
    time-zone: Asia/Seoul

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka/ # 유레카 서버 주소

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

schedule:
  cron: "0 0/1 * * * *"
  use: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

# 개발환경
#logging:
#  level:
#    root: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
